# Generated by Django 5.1.4 on 2026-06-13 15:26

import django.db.models.deletion
import scenarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon name, e.g. 🛂', max_length=50)),
                ('name', models.JSONField(default=scenarios.models.empty_translations, help_text='{"uz": "...", "ru": "...", "en": "..."}')),
                ('description', models.JSONField(blank=True, default=scenarios.models.empty_translations)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.JSONField(default=scenarios.models.empty_translations)),
                ('body', models.JSONField(default=scenarios.models.empty_translations, help_text='Markdown-capable, per language.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='scenarios.category')),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
    ]
